---
title: "Feature Selection Using Black Hole Optimization"
subtitle: "Study Case Crime Level Database"
author: "Mohammad Rizka Fadhli"
date: "2/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
setwd("~/209_ITB/Meta Heuristics/Black Hole/regresi")

library(dplyr)
library(ggplot2)
```

```{r}
data = read.csv("crime.csv") %>% janitor::clean_names()
colnames(data) = c("id","percent_m", "is_south", "mean_education", "police_exp60", 
                   "police_exp59", "labour_participation", "m_per1000f", "state_pop", 
                   "nonwhites_per1000", "unemploy_m24", "unemploy_m39", "gdp", "inequality", 
                   "prob_prison", "time_prison", "crime_rate")

data
```

```{r}
target = data$inequality
data = data %>% select(-id,-inequality)

nama_var = colnames(data)

N = 20
star = vector("list",N)

for(i in 1:N){
  calon = runif(15,0,1)
  star[[i]] = calon
}

# set obj function
obj_funct = function(list){
  bound = round(list,0)
  predictor = nama_var[bound == 1]
  df_reg = data[predictor]
  df_reg$target = target
  
  model = lm(target ~ .,df_reg)
  hasil = summary(model)
  r_sq = hasil$adj.r.squared
  return(r_sq)
}

# set constraint 1
batas1 = function(list){
  bound = round(list,0)
  sqrt(sum(bound^2)) - sqrt(15)
}

# set constraint 2
batas2 = function(list){
  bound = round(list,0)
  1 - sqrt(sum(bound^2))
}

beta = 9999999

# function keseluruhan
f_tot = function(list){
  - obj_funct(list) + max((beta * batas1(list)),0) + max((beta * batas2(list)),0)
}

f_hit = c()

for (i in 1:N){
  temp = f_tot(star[[i]])
  f_hit[i] = temp
}

f_hit

n_bhole = which.min(f_hit)
```
