---
title: "UJIAN TENGAH SEMESTER I"
subtitle: "SK5001 Analisis Numerik Lanjut"
author: |
  | Mohammad Rizka Fadhli
  | NIM: 20921004
output:
  pdf_document:
   dev: png
   toc: false
   number_section: false
---

```{r,include=FALSE}
options(digit = 5)
rm(list=ls())
library(dplyr)
library(ggplot2)
```

# Beberapa Function yang Berguna

```{r}
# membuat matrix n x n secara random
bikin_matrix = function(n){
  # membuat matrix random n x n
  v = sample(0:9,n^2,replace = T)
  A = matrix(v,byrow = T,ncol = n)
  return(A)
}

# misal matriks A n x n
n = 3
A = bikin_matrix(n)

# menghitung inverse
solve(A)

# pembuktian A * A^(-1) = I
A %*% solve(A)

# menghitung determinan
det(A)

# mencari nilai eigen
eigen(A)

# melakukan transpose
t(A)

# menghitung norm infinity
norm(A,"I")

# mengalikan matriks dengan vector
# misal
b = sample(0:9,n,replace = T)
A %*% b

# mengekstrak diagonal dari matrix
diag(A)

# membuat matriks diagonal n x n dari berisi bilangan tertentu
x = sample(0:9,n,replace = T)
diag(x)

# membuat matriks identitas n x n
diag(1,n)
```
