---
title: "P2MS-ITB TEACHING FACTORY-NETWORK"
subtitle: "Basic Market Research"
author: "Mohammad Rizka Fadhli<br>ikanx101@gmail.com"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r,include=FALSE}
rm(list=ls())
library(dplyr)
```

# Tujuan Kuliah

Kuliah ___Basic Market Research___ dirancang untuk:

1. Menambah pengetahuan peserta kuliah terhadap _market research_ dan peranannya dalam dunia bisnis sebagai salah satu _decision support system_. Kelak akan dijelaskan pula berbagai jenis _research_ yang lazim digunakan seperti:
	1. _Qualitative research_: _focus group discussion_ (FGD), _In-depth Interview_ (IDI), dan _qualitative observation_.
	1. _Quantitative research_: _surveys_ dan _quantitative observation_.
1. Mengenalkan beberapa studi _market research_ yang lazim dilakukan di dunia bisnis, seperti:
	1. _Market Entry Study_.
	1. _TV Campaign Research_, meliputi _storyline research_, _pre-campaign research_, dan _post-campaign research_.
	1. _Brand Health Research_, meliputi _satisfaction_, _loyalty_, _usership_, _perception_, dan sebagainya.
	1. _Media Habit_.
	1. _Consumer Profile_.
	1. _Service Audit_.
	1. _Retail Audit_.
1. Memberikan pengalaman terhadap mahasiswa untuk merencanakan, menyusun, melakukan, dan membuat laporan suatu _market research_ sederhana. Tahapan-tahapan yang akan dilakukan:
	1. Formulasi masalah:
		- Mengubah _management problem_ menjadi _research problem_.
		- Menggunakan _tools_ seperti _interrelationship diagram_ untuk memisahkan antara `sebab` dan `akibat` dari suatu masalah.
	1. Menuliskan tujuan _research_.
	1. Melakukan _sample design_.
