---
title: "Belajar Curve Fitting"
subtitle: "Cobain dulu yah"
output: github_document
---

```{r,include = FALSE}
# mulai dari nol
rm(list=ls())

# libraries
library(dplyr)
library(ggplot2)
```

# CURVE FITTING

Kita akan belajar dulu dari dasarnya. Kita juga akan lihat dan bandingkan cara pengerjaan dengan algoritma bikinan sendiri dan algoritma dar `base` __R__.

## Linear _Curve Fitting_

Sering disebut sebagai regresi linear.

```{r}
# ini data contoh
x = c(32,64,96,118,126,144,152.5,158)
y = c(99.5,104.8,108.5,100,86,64,35.3,15)

# we will make y the response variable and x the predictor
# the response variable is usually on the y-axis
plot(x,y,pch=19)

```

Untuk membuat model linear, kita bisa gunakan `base` __R__ via `lm()`. Berikut adalah caranya:

```{r}
# linear regression
model1 = lm(y~x)
model1
```

```{r}
n = length(x)
sum_xi = sum(x)
sum_xi_xi = sum(x^2)
sum_xi_yi = sum(x*y)
sum_yi = sum(y)

A = matrix(c(n,sum_xi,sum_xi,sum_xi_xi),nrow = 2,byrow = T)
A
A_inv = solve(A)
A_inv
b = c(sum_yi,sum_xi_yi)

A_inv %*% b
```
