---
title: "Laporan Akhir Penelitian Mandiri dalam Sains Komputasi IV"
subtitle: Model Optimisasi
author: | 
    | Mohammad Rizka Fadhli 
    | Program Studi Magister Sains Komputasi
    | Fakultas Matematika dan Ilmu Pengetahuan Alam
    | Institut Teknologi Bandung
    | 20921004@mahasiswa.itb.ac.id
date: "`r format(Sys.time(), '%d %B %Y')`"
fontsize: 12pt
output: 
  pdf_document:
    number_sections: true
    toc: false
    fig_width: 7
    fig_height: 4
    fig_caption: true
    highlight: breezedark
bibliography: references.bib
csl: academic-psychiatry.csl
linestretch: 1.75
colorlinks: true
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot[CO,CE]{20921004@mahasiswa.itb.ac.id}
- \fancyfoot[LE,RO]{hal \thepage}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(dplyr)
```

\newpage
\tableofcontents
\newpage
\listoffigures
\newpage
\listoftables

\newpage

# LATAR BELAKANG

Semenjak diperkenalkan pertama kali pada tahun 1982, _Supply Chain Management_ (SCM) memegang peranan penting dalam manufaktur sebagai suatu sistem produksi terintegrasi [@webber]. Di dalam SCM, bahan baku dibeli perusahaan dari berbagai _supplier_, dibuat ke dalam suatu produk yang kemudian akan dijual ke pelanggan melalui berbagai _channel_ distribusi.

Dalam mengarungi kompetisi, perusahaan perlu memahami dua faktor kunci, yakni _cost reduction_ dan _product quality_ [@masood]. Kedua faktor ini sangat bergantung pada pemilihan _supplier_ yang tepat. Sehingga proses _supplier selection_ menjadi proses yang krusial dalam setiap perusahaan.

Dalam prakteknya, perusahaan bisa menggunakan dua strategi terkait _supplier selection_, yakni: _single sourcing_ dan _multiple sourcing_. _Single sourcing_ berarti perusahaan hanya membeli bahan baku dari _supplier_ tunggal. Sedangkan _multiple sourcing_ berarti perusahaan bisa membeli bahan baku dari beberapa _supplier_. Strategi _single sourcing_ bisa menaikkan level risiko dari perusahaan sedangkan strategi _multiple sourcing_ menyebabkan _initial cost_ dan _ongoing cost_ yang lebih besar [@sourcing]. Bagi perusahaan yang menerapkan strategi _multiple sourcing_, banyak faktor yang akan membuat kompleks pengambilan keputusan. Misalnya harga, perjanjian transaksi, kualitas, kuantitas, jarak dan biaya pengantaran [@masood].

PT. NFI adalah salah satu perusahaan manufaktur di Indonesia yang memproduksi 130 jenis minuman. Salah satu bahan baku yang paling sering digunakan untuk semua produk minuman tersebut adalah gula. Untuk pemenuhan bahan baku gula, NFI menggunakan prinsip _multiple sourcing_ dengan perjanjian untuk memasoknya dari enam buah _supplier_. Spesifikasi bahan baku gula dan harga perton berbeda-beda antar _supplier_.

Pada penelitian ini, ada tiga masalah utama yang hendak diselesaikan, yakni:

- Memilih _supplier_ bahan baku.
- Menentukan banyaknya bahan baku yang harus dibeli dari suatu _supplier_.
- Menentukan bahan baku mana yang harus digunakan untuk memproduksi setiap produk.

dengan tujuan total biaya pembelian seminim mungkin tetapi memenuhi kebutuhan yang ada pada periode tertentu. Luaran dari penelitian ini adalah suatu model optimisasi yang bisa menyelesaikan permasalahan di atas.

Laporan akhir penelitian mandiri dalam sains komputasi III ini adalah: _data collection_ dan dokumentasi _production system_ untuk penelitian berjudul _Optimization Method for Supplier Selection, Order Allocation, and Incorporating Raw-Material Characteristic: Case Study Beverages Manufacture_.


# MODEL OPTIMISASI

Masalah _supplier selection_, _order allocation_, dan pemasangan bahan baku dengan produk adalah masalah dengan satu kriteria, yaitu total harga pengadaan (pembelian) tetapi ukuran masalahnya lebih besar karena ketiga masalah di atas hanya sebagian dari variabel keputusan. Variabel keputusan lainnya adalah bagaimana distribusi pengiriman dari tiap _supplier_ per minggu. Oleh karena itu, masalah krusial pertama dari penyelesaian masalah ini adalah menurunkan masalah optimisasi yang tepat yang dapat menjadi model dari masalah ini.

Berdasarkan informasi-informasi yang telah didapatkan dari `Penelitian Mandiri III`, berikut adalah model optimisasi dari permasalahan ini.

## Parameter yang Diketahui

Notasikan:

- $M$ sebagai himpunan semua minggu. 
    - $\hat{M} \setminus \{1,6\}$
- $P = P_1 \bigcup P_2 \bigcup P_3 \bigcup P_4 \bigcup P_5 \bigcup P_6$ sebagai himpunan produk di semua minggu.
    - $\hat{P}$ sebagai himpunan bagian dari $P$, yakni himpunan produk yang menggunakan minimal dua jenis bahan baku.
    - $\dot{P}$ sebagai himpunan bagian dari $P$, yakni himpunan produk yang menggunakan satu jenis bahan baku saja.
- $G = \{1,2,3,4,5,6\}$ sebagai himpunan bahan baku.
- $D$ sebagai kebutuhan bahan baku di bulan perencanaan, yaitu: _week_ 3 - 6.
- $maxcap$ sebagai kapasitas gudang bahan baku.
- $\forall k \in G, Pr_k$ adalah total proporsi portofolio bahan baku yang ditetapkan dalam setahun (dalam ton).
- $\forall i \in P_j, \space g_{ijk}$ adalah kebutuhan bahan baku (dalam ton) dari produk $i$ pada _week_ $k$.
- $\forall k \in G, \space c_k$ adalah harga bahan baku $k$ per ton.
- $\forall k \in G, \space \epsilon_k$ adalah _minimum order quantity_ dari bahan baku $k$.
- $\forall k \in G, \space \hat{d}_{2k}$ adalah total bahan baku $k$ yang dibutuhkan pada _week_ 2.
- $\forall k \in G, \space Z_{ik}$ adalah stok level bahan baku $k$ di gudang pada akhir _week_ 1.

## Variabel Keputusan

### Variabel I {.unnumbered .unlisted}

Definisikan $\forall k \in G, \space x_k$ adalah banyaknya bahan baku $k$ yang dibeli.

Berdasarkan informasi sebelumnya, kita ketahui bahwa $x_k$ bernilai bulat positif dan harus lebih besar atau sama dengan nilai $\epsilon_k$. Kemudian tidak ada kewajiban untuk membeli bahan baku dari seluruh _supplier_. 

Maka kita bisa tuliskan: $x_k = 0$ atau $\epsilon_k \leq x_k \leq maxcap$. Untuk menghindari nilai diskontinu dari $x_k$ ini, definisikan:

$$y_k = \left\{\begin{matrix}
1, & x_k = 0 \\ 0, & \epsilon_k \leq x_k \leq maxcap
\end{matrix}\right.$$

$\forall j \in M  \setminus \{1,6\}, \forall i \in P_j, \forall k \in G$,

### Variabel II {.unnumbered .unlisted}

Definisikan: $\hat{x}_{jk}$ sebagai banyaknya pengiriman bahan baku jenis $k$ di awal _week_ $j$.

$$a_{ijk} = \left\{\begin{matrix}
1, & \text{produk ke } i \text{ di week } j \text{ menggunakan BB } k \\ 
0, & \text{lainnya}
\end{matrix}\right.$$

### Variabel III {.unnumbered .unlisted}

Definisikan: $b_{ijk}$ sebagai proporsi penggunaan bahan baku $k$ dari seluruh kebutuhan bahan baku untuk produk $i$ di _week_ $j$, $\forall j \in M \setminus \{ 1 \}, \forall k \in G$.

### Variabel IV {.unnumbered .unlisted}

Definisikan: $z_{jk}$ sebagai stok level bahan baku $k$ di akhir _week_ $j$.


## Kendala Optimisasi

### Kendala I {.unnumbered .unlisted}

Kendala I adalah penghubung yang benar antara variabel keputusan biner, integer, atau kontinu yang berkaitan:

$$\begin{matrix}
\forall k \in G, &  \\
 & x_k \leq Dy_k \\
 & x_k \geq \epsilon y_k \\
\forall j \in M \setminus \{ 1,2 \}, \forall i \in P_j, \forall k \in G, & \\
 & b_{ijk} \leq a_{ijk} \\
 & b_{ijk} \geq \mu a_{ijk}
\end{matrix}$$

untuk suatu nilai $\mu$ yang kecil.

### Kendala II {.unnumbered .unlisted}

Kendala II dibuat agar total bahan baku yang dipesan tidak kurang dari total _demand_ di bulan perencanaan.

$$\sum_{k \in G} x_k \geq D$$

### Kendala III {.unnumbered .unlisted}

Kendala III mengatur hubungan antara total pembelian bahan baku dan pengiriman setiap minggu.

$$\begin{matrix}
\forall k \in G, & \\
 & x_k = \sum_{j \in \hat{M}} \hat{x}_{jk}
\end{matrix}$$

### Kendala IV {.unnumbered .unlisted}

Kendala IV berfungsi untuk menjaga komposisi bahan baku yang diinginkan.

$$\begin{matrix}
\forall j \in M \setminus \{ 1,2 \}, \space \forall i \in \hat{P}_j, & \\
 & \sum_{k \in G} a_{ijk} \geq 2 \\
 & \sum_{k \in G} b_{ijk} = 1 \\
\forall j \in M \setminus \{ 1,2 \}, \space \forall i \in \dot{P}_j, & \\ 
 & \sum_{k \in G} a_{ijk} = 1 \\
 & \sum_{k \in G} b_{ijk} = 1
\end{matrix}$$

### Kendala V {.unnumbered .unlisted}

Kendala V berfungsi untuk menjaga stok level sesaat setelah pengiriman bahan baku agar tidak melebihi kapasitas gudang.

$$\begin{matrix}
 & \sum_{k \in G} (Z_{1k} + \hat{x}_{1k} - \hat{d}_{2k} + z_{jk}) = maxcap \\
\forall j \in M \setminus \{ 1,2 \} & \\
 & \sum_{k \in G} (z_{(j-1)k} + \hat{x}_{(j-1)k}) - \sum_{i \in P_j} b_{ijk} g_{ijk} + z_{jk} = maxcap
\end{matrix}$$

### Kendala VI {.unnumbered .unlisted}

Kendala VI menjaga agar pembelian bahan baku tidak melebihi proporsi portofolio yang sudah ditetapkan dalam setahun.

$$\sum_{k \in G} x_k \leq Pr_k$$


## Fungsi Objektif

Permasalahan yang dihadapi adalah pemilihan _supplier_ dan bahan baku sebagai berikut:

$$\min \sum_{k \in G} c_k x_k$$

$$\begin{matrix}
\text{terhadap kendala I sampai VI dan } \\
x_k = 0 \text{ atau } \epsilon_k \leq x_k \leq maxcap, \space x_k \in \mathbb{Z}^+ \\
y_k \in \{ 0,1 \}, \hat{x}_{jk} \geq 0, a_{ijk} \in \{ 0,1 \} \\
0 \leq b_{ijk} \leq 1 \\
0 \leq z_{jk} \leq maxcap \\
\end{matrix}$$


\newpage

# REFERENSI